### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by yadirhb** [npm/metavuln-calculator#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When executing npm cli commands, example: `npm audit --audit-level=moderate`:

```
npm audit --audit-level=moderate                                       
npm ERR! Cannot convert undefined or null to object

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yadirbatista/.npm/_logs/2023-03-15T14_42_49_384Z-debug-0.log
```

When I dug a little into the logs by running: `cat /Users/yadirbatista/.npm/_logs/2023-03-15T14_42_49_384Z-debug-0.log` I get this:

```
249 verbose stack TypeError: Cannot convert undefined or null to object
249 verbose stack     at Function.keys (<anonymous>)
249 verbose stack     at Advisory.load (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:109:33)
249 verbose stack     at [calculate] (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:60:14)
249 verbose stack     at async Promise.all (index 0)
249 verbose stack     at async [init] (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:188:9)
249 verbose stack     at async AuditReport.run (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:109:7)
249 verbose stack     at async Arborist.audit (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/audit.js:37:24)
249 verbose stack     at async Audit.auditAdvisories (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/lib/commands/audit.js:390:5)
249 verbose stack     at async Audit.exec (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/lib/commands/audit.js:374:7)
249 verbose stack     at async module.exports (/Users/yadirbatista/.nvm/versions/node/v18.11.0/lib/node_modules/npm/lib/cli.js:78:5)
```

I have a solution for the issue, it's a minor fix to cover untested assumptions: for example:
```
// lib/advisory.js:109: 
const pakuVersions = Object.keys(packument.versions)
``` 
assumes that packument.versions always exists and it's an object. Solution:
```
const pakuVersions = packument.versions ? Object.keys(packument.versions) : []
```
Another issue in line 245 related with packument.versions:
```
// lib/advisory.js:245
const mani = this[_packument].versions[version] || {
      dependencies: {
        [this.dependency]: spec,
      },
    }
```
Solution:
```
const mani = this[_packument].versions && this[_packument].versions[version] ? this[_packument].versions[version] : {
      dependencies: {
        [this.dependency]: spec,
      },
    }
```

### Expected Behavior

I expect npm to run fine.

### Steps To Reproduce

1. I have only seen this happen in one repository and it's a private source. I'm not sure if you can reproduce it.

### Environment

- npm: All versions
- Node: 16*, 18*
- OS: Unix
- platform: arm64 (Ubuntu, Alpine, Mac OS)

**Comment by yadirhb** [comment]
Added solution PR: https://github.com/npm/metavuln-calculator/pull/81

**Comment by yadirhb** [comment]
Reported this issue on npm-cli: https://github.com/npm/cli/issues/6258

**Comment by yadirhb** [comment]
Any news on this? This is still ongoing and a solution has been provided...

**Comment by wraithgar** [comment]
How can you have a packument with no versions?

**Comment by wraithgar** [comment]
`https://github.com/npm/npm-pick-manifest/blob/main/lib/index.js#L41` npm-pick-manifest defaults this to `{}`

**Comment by wraithgar** [comment]
Packuments only have no `versions` when they've been unpublished, and shouldn't be in your tree at that point.

If someone comes up with a good reproduction case for when this code is hit outside of that situation please open a new issue.

**Comment by rainabba** [comment]
`how can you have a packument with no versions` I don't know, but this code is not robust to deal with the very real circumstance where it is, so rather than focusing on ideals, can we please just get code in place that doesn't fail on `npm i`?

**Comment by rainabba** [comment]
I have been unable to tell which of our project dependencies are resolving to metavuln-calculator (perhaps for the same reason there's no `packument` in the failing context) but this dependency IS getting installed and IS failing because it's not gracefully failing with an explanation and so `npm i` does not complete. Because it doesn't, we also don't get a package-lock.json to further look into.

Here is the error during `npm i`:
```npm-log
427 http fetch GET 200 https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.348.tgz 4156ms (cache miss)
3428 timing reifyNode:node_modules/electron-to-chromium Completed in 4506ms
3429 http fetch GET 200 https://registry.npmjs.org/wp-context 1861ms (cache revalidated)
3430 timing metavuln:packument:wp-context Completed in 1861ms
3431 verbose stack TypeError: Cannot convert undefined or null to object
3431 verbose stack     at Function.keys (<anonymous>)
3431 verbose stack     at Advisory.load (/src/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:109:33)
3431 verbose stack     at Calculator.[calculate] (/src/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:60:14)
3431 verbose stack     at async Promise.all (index 4)
3431 verbose stack     at async Map.[init] (/src/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:188:9)
3431 verbose stack     at async Map.run (/src/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:109:7)
```

I believe you are mistaken in closing these down while there is still a clear and reproducable error and [my PR](https://github.com/npm/metavuln-calculator/pull/83) should be re-opened. 

If I am confused, I would be grateful for clarification.

**Comment by rainabba** [comment]
`npx npm-remote-ls @npmcli/arborist` (the package next up in the crash stack) returned the following (filtered) and to me that looks like an infinite loop. Thoughts? Perhaps the reason the uncovered-scenario is being exposed?

```
└─ @npmcli/arborist@6.2.6
   ├─ @npmcli/template-oss@4.12.1
   │  ├─ @npmcli/arborist@6.2.6
```

**Comment by rainabba** [comment]
We don't seem to be encountering this when we're deplaying for Node 14.x so it seems that different versions of Node/NPM yield different results. 

I don't understand why this issue is still closed. Can anyone help me understand? It feels like the repo's been abandoned.

**Comment by rainabba** [comment]
Thank you for that. 

There's always room for varying opinions, but isn't the crash in this module? Even if it's a bad call from elsewhere, shouldn't this module handle that bad call gracefully? I'm pretty sure a few of us are here for the same reason; the issue is here. I can understand that there may still be a larger issue, but why not improve this code [also]?

The fact that our fix requires additional testing for coverage implies to me that there were/are missing tests in this repo. No? If this code was properly checking, then it could report issues rather than "just crashing" at the least. 

With my PR, we might at least get a more meaninful error wouldn't we?
