### ISSUE TITLE
[BUG] Cannot convert undefined or null to object in case of installing a dependency from github

### ISSUE THREAD

**Issue by vigan-abd** [npm/metavuln-calculator#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So when running npm install with package https://github.com/bitfinexcom/bfx-svc-test-helper as dependency we're getting this error:
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Cannot convert undefined or null to object

npm ERR! A complete log of this run can be found in: /***/.npm/_logs/2023-04-03T12_54_25_036Z-debug-0.log
```

### Expected Behavior

successful npm installation

### Steps To Reproduce

try this:
```
npm i https://github.com/bitfinexcom/bfx-svc-test-helper
```

### Environment

- npm: 9.6.3
- Node: v14.18.3
- OS: Ubuntu 22.04
- platform: PC

**Comment by vigan-abd** [comment]
is it ok if we open a PR to make pakumen versions optional?

**Comment by wraithgar** [comment]
Yes but you'll need to make sure the tests pass and coverage is all there. Folks in the past submitted code-only PRs and bailed on the tests.

**Comment by vigan-abd** [comment]
hey @wraithgar @rainabba  opened PR https://github.com/npm/metavuln-calculator/pull/85 with optional chaining (supported from node 14.0.0) and also included test case to keep coverage 100%
